### ISSUE TITLE
UI: Add keyboard controls ⌨

### ISSUE THREAD

**Issue by wh0sumit** [rogue-kitten/weather-app#1]
If we could add keyboard controls to the search results, it would be great. 

- ctrl + s -- to directly opens the search box.
- up & down key -- to navigate through the results. 
- enter -- to search the selected input.

**Comment by rogue-kitten** [comment]
Hi Sumit, thanks for the suggestions. The changes have been incorporated into the App now. Here is the key map. 

- Ctrl + k -> to open the search bar
- Arrow Keys -> to cycle through the search results
- Enter -> to select a particular search input
- Ctrl + c -> to toggle the temperature unit
- Ctrl + Enter -> to get the temperature data 

Closing this issue now. If you have any other suggestions, feel free to open another issue.

**Comment by wh0sumit** [comment]
looks really cool, nash 🙌🚀
